<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="6" failures="0" skipped="0" tests="6" time="0.866" timestamp="2024-09-26T20:36:15.577618" hostname="827K3X2"><testcase classname="tests.test_goto_py_page" name="test_simple_go3_to_python_page[firefox]" time="0.209"><error message="failed on setup with &quot;playwright._impl._errors.Error: BrowserType.launch: Executable doesn't exist at /home/vtkachenko/.cache/ms-playwright/firefox-1447/firefox/firefox&#10;╔════════════════════════════════════════════════════════════╗&#10;║ Looks like Playwright was just installed or updated.       ║&#10;║ Please run the following command to download new browsers: ║&#10;║                                                            ║&#10;║     playwright install                                     ║&#10;║                                                            ║&#10;║ &lt;3 Playwright Team                                         ║&#10;╚════════════════════════════════════════════════════════════╝&quot;">launch_browser = &lt;function launch_browser.&lt;locals&gt;.launch at 0x7ff679af7550&gt;

&gt;   ???

/home/vtkachenko/Projects/studu/venv/lib/python3.8/site-packages/pytest_playwright/pytest_playwright.py:220: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/home/vtkachenko/Projects/studu/venv/lib/python3.8/site-packages/pytest_playwright/pytest_playwright.py:212: in launch
    ???
../../venv/lib/python3.8/site-packages/playwright/sync_api/_generated.py:13914: in launch
    self._sync(
../../venv/lib/python3.8/site-packages/playwright/_impl/_browser_type.py:94: in launch
    Browser, from_channel(await self._channel.send("launch", params))
../../venv/lib/python3.8/site-packages/playwright/_impl/_connection.py:59: in send
    return await self._connection.wrap_api_call(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = &lt;playwright._impl._connection.Connection object at 0x7ff67a36dcd0&gt;
cb = &lt;function Channel.send.&lt;locals&gt;.&lt;lambda&gt; at 0x7ff67a3890d0&gt;
is_internal = False

    async def wrap_api_call(
        self, cb: Callable[[], Any], is_internal: bool = False
    ) -&gt; Any:
        if self._api_zone.get():
            return await cb()
        task = asyncio.current_task(self._loop)
        st: List[inspect.FrameInfo] = getattr(task, "__pw_stack__", inspect.stack())
        parsed_st = _extract_stack_trace_information_from_stack(st, is_internal)
        self._api_zone.set(parsed_st)
        try:
            return await cb()
        except Exception as error:
&gt;           raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
E           playwright._impl._errors.Error: BrowserType.launch: Executable doesn't exist at /home/vtkachenko/.cache/ms-playwright/firefox-1447/firefox/firefox
E           ╔════════════════════════════════════════════════════════════╗
E           ║ Looks like Playwright was just installed or updated.       ║
E           ║ Please run the following command to download new browsers: ║
E           ║                                                            ║
E           ║     playwright install                                     ║
E           ║                                                            ║
E           ║ &lt;3 Playwright Team                                         ║
E           ╚════════════════════════════════════════════════════════════╝

../../venv/lib/python3.8/site-packages/playwright/_impl/_connection.py:513: Error</error></testcase><testcase classname="tests.test_goto_py_page" name="test_second3_test[firefox]" time="0.000"><error message="failed on setup with &quot;playwright._impl._errors.Error: BrowserType.launch: Executable doesn't exist at /home/vtkachenko/.cache/ms-playwright/firefox-1447/firefox/firefox&#10;╔════════════════════════════════════════════════════════════╗&#10;║ Looks like Playwright was just installed or updated.       ║&#10;║ Please run the following command to download new browsers: ║&#10;║                                                            ║&#10;║     playwright install                                     ║&#10;║                                                            ║&#10;║ &lt;3 Playwright Team                                         ║&#10;╚════════════════════════════════════════════════════════════╝&quot;">launch_browser = &lt;function launch_browser.&lt;locals&gt;.launch at 0x7ff679af7550&gt;

&gt;   ???

/home/vtkachenko/Projects/studu/venv/lib/python3.8/site-packages/pytest_playwright/pytest_playwright.py:220: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/home/vtkachenko/Projects/studu/venv/lib/python3.8/site-packages/pytest_playwright/pytest_playwright.py:212: in launch
    ???
../../venv/lib/python3.8/site-packages/playwright/sync_api/_generated.py:13914: in launch
    self._sync(
../../venv/lib/python3.8/site-packages/playwright/_impl/_browser_type.py:94: in launch
    Browser, from_channel(await self._channel.send("launch", params))
../../venv/lib/python3.8/site-packages/playwright/_impl/_connection.py:59: in send
    return await self._connection.wrap_api_call(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = &lt;playwright._impl._connection.Connection object at 0x7ff67a36dcd0&gt;
cb = &lt;function Channel.send.&lt;locals&gt;.&lt;lambda&gt; at 0x7ff67a3890d0&gt;
is_internal = False

    async def wrap_api_call(
        self, cb: Callable[[], Any], is_internal: bool = False
    ) -&gt; Any:
        if self._api_zone.get():
            return await cb()
        task = asyncio.current_task(self._loop)
        st: List[inspect.FrameInfo] = getattr(task, "__pw_stack__", inspect.stack())
        parsed_st = _extract_stack_trace_information_from_stack(st, is_internal)
        self._api_zone.set(parsed_st)
        try:
            return await cb()
        except Exception as error:
&gt;           raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
E           playwright._impl._errors.Error: BrowserType.launch: Executable doesn't exist at /home/vtkachenko/.cache/ms-playwright/firefox-1447/firefox/firefox
E           ╔════════════════════════════════════════════════════════════╗
E           ║ Looks like Playwright was just installed or updated.       ║
E           ║ Please run the following command to download new browsers: ║
E           ║                                                            ║
E           ║     playwright install                                     ║
E           ║                                                            ║
E           ║ &lt;3 Playwright Team                                         ║
E           ╚════════════════════════════════════════════════════════════╝

../../venv/lib/python3.8/site-packages/playwright/_impl/_connection.py:513: Error</error></testcase><testcase classname="tests.test_goto_py_page" name="test_thir3d_test[firefox]" time="0.000"><error message="failed on setup with &quot;playwright._impl._errors.Error: BrowserType.launch: Executable doesn't exist at /home/vtkachenko/.cache/ms-playwright/firefox-1447/firefox/firefox&#10;╔════════════════════════════════════════════════════════════╗&#10;║ Looks like Playwright was just installed or updated.       ║&#10;║ Please run the following command to download new browsers: ║&#10;║                                                            ║&#10;║     playwright install                                     ║&#10;║                                                            ║&#10;║ &lt;3 Playwright Team                                         ║&#10;╚════════════════════════════════════════════════════════════╝&quot;">launch_browser = &lt;function launch_browser.&lt;locals&gt;.launch at 0x7ff679af7550&gt;

&gt;   ???

/home/vtkachenko/Projects/studu/venv/lib/python3.8/site-packages/pytest_playwright/pytest_playwright.py:220: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/home/vtkachenko/Projects/studu/venv/lib/python3.8/site-packages/pytest_playwright/pytest_playwright.py:212: in launch
    ???
../../venv/lib/python3.8/site-packages/playwright/sync_api/_generated.py:13914: in launch
    self._sync(
../../venv/lib/python3.8/site-packages/playwright/_impl/_browser_type.py:94: in launch
    Browser, from_channel(await self._channel.send("launch", params))
../../venv/lib/python3.8/site-packages/playwright/_impl/_connection.py:59: in send
    return await self._connection.wrap_api_call(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = &lt;playwright._impl._connection.Connection object at 0x7ff67a36dcd0&gt;
cb = &lt;function Channel.send.&lt;locals&gt;.&lt;lambda&gt; at 0x7ff67a3890d0&gt;
is_internal = False

    async def wrap_api_call(
        self, cb: Callable[[], Any], is_internal: bool = False
    ) -&gt; Any:
        if self._api_zone.get():
            return await cb()
        task = asyncio.current_task(self._loop)
        st: List[inspect.FrameInfo] = getattr(task, "__pw_stack__", inspect.stack())
        parsed_st = _extract_stack_trace_information_from_stack(st, is_internal)
        self._api_zone.set(parsed_st)
        try:
            return await cb()
        except Exception as error:
&gt;           raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
E           playwright._impl._errors.Error: BrowserType.launch: Executable doesn't exist at /home/vtkachenko/.cache/ms-playwright/firefox-1447/firefox/firefox
E           ╔════════════════════════════════════════════════════════════╗
E           ║ Looks like Playwright was just installed or updated.       ║
E           ║ Please run the following command to download new browsers: ║
E           ║                                                            ║
E           ║     playwright install                                     ║
E           ║                                                            ║
E           ║ &lt;3 Playwright Team                                         ║
E           ╚════════════════════════════════════════════════════════════╝

../../venv/lib/python3.8/site-packages/playwright/_impl/_connection.py:513: Error</error></testcase><testcase classname="tests.test_goto_py_page" name="test_simple_go3_to_python_page[chromium]" time="0.005"><error message="failed on setup with &quot;playwright._impl._errors.Error: BrowserType.launch: Executable doesn't exist at /home/vtkachenko/.cache/ms-playwright/chromium-1112/chrome-linux/chrome&#10;╔════════════════════════════════════════════════════════════╗&#10;║ Looks like Playwright was just installed or updated.       ║&#10;║ Please run the following command to download new browsers: ║&#10;║                                                            ║&#10;║     playwright install                                     ║&#10;║                                                            ║&#10;║ &lt;3 Playwright Team                                         ║&#10;╚════════════════════════════════════════════════════════════╝&quot;">launch_browser = &lt;function launch_browser.&lt;locals&gt;.launch at 0x7ff67982a670&gt;

&gt;   ???

/home/vtkachenko/Projects/studu/venv/lib/python3.8/site-packages/pytest_playwright/pytest_playwright.py:220: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/home/vtkachenko/Projects/studu/venv/lib/python3.8/site-packages/pytest_playwright/pytest_playwright.py:212: in launch
    ???
../../venv/lib/python3.8/site-packages/playwright/sync_api/_generated.py:13914: in launch
    self._sync(
../../venv/lib/python3.8/site-packages/playwright/_impl/_browser_type.py:94: in launch
    Browser, from_channel(await self._channel.send("launch", params))
../../venv/lib/python3.8/site-packages/playwright/_impl/_connection.py:59: in send
    return await self._connection.wrap_api_call(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = &lt;playwright._impl._connection.Connection object at 0x7ff67a36dcd0&gt;
cb = &lt;function Channel.send.&lt;locals&gt;.&lt;lambda&gt; at 0x7ff679897b80&gt;
is_internal = False

    async def wrap_api_call(
        self, cb: Callable[[], Any], is_internal: bool = False
    ) -&gt; Any:
        if self._api_zone.get():
            return await cb()
        task = asyncio.current_task(self._loop)
        st: List[inspect.FrameInfo] = getattr(task, "__pw_stack__", inspect.stack())
        parsed_st = _extract_stack_trace_information_from_stack(st, is_internal)
        self._api_zone.set(parsed_st)
        try:
            return await cb()
        except Exception as error:
&gt;           raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
E           playwright._impl._errors.Error: BrowserType.launch: Executable doesn't exist at /home/vtkachenko/.cache/ms-playwright/chromium-1112/chrome-linux/chrome
E           ╔════════════════════════════════════════════════════════════╗
E           ║ Looks like Playwright was just installed or updated.       ║
E           ║ Please run the following command to download new browsers: ║
E           ║                                                            ║
E           ║     playwright install                                     ║
E           ║                                                            ║
E           ║ &lt;3 Playwright Team                                         ║
E           ╚════════════════════════════════════════════════════════════╝

../../venv/lib/python3.8/site-packages/playwright/_impl/_connection.py:513: Error</error></testcase><testcase classname="tests.test_goto_py_page" name="test_second3_test[chromium]" time="0.000"><error message="failed on setup with &quot;playwright._impl._errors.Error: BrowserType.launch: Executable doesn't exist at /home/vtkachenko/.cache/ms-playwright/chromium-1112/chrome-linux/chrome&#10;╔════════════════════════════════════════════════════════════╗&#10;║ Looks like Playwright was just installed or updated.       ║&#10;║ Please run the following command to download new browsers: ║&#10;║                                                            ║&#10;║     playwright install                                     ║&#10;║                                                            ║&#10;║ &lt;3 Playwright Team                                         ║&#10;╚════════════════════════════════════════════════════════════╝&quot;">launch_browser = &lt;function launch_browser.&lt;locals&gt;.launch at 0x7ff67982a670&gt;

&gt;   ???

/home/vtkachenko/Projects/studu/venv/lib/python3.8/site-packages/pytest_playwright/pytest_playwright.py:220: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/home/vtkachenko/Projects/studu/venv/lib/python3.8/site-packages/pytest_playwright/pytest_playwright.py:212: in launch
    ???
../../venv/lib/python3.8/site-packages/playwright/sync_api/_generated.py:13914: in launch
    self._sync(
../../venv/lib/python3.8/site-packages/playwright/_impl/_browser_type.py:94: in launch
    Browser, from_channel(await self._channel.send("launch", params))
../../venv/lib/python3.8/site-packages/playwright/_impl/_connection.py:59: in send
    return await self._connection.wrap_api_call(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = &lt;playwright._impl._connection.Connection object at 0x7ff67a36dcd0&gt;
cb = &lt;function Channel.send.&lt;locals&gt;.&lt;lambda&gt; at 0x7ff679897b80&gt;
is_internal = False

    async def wrap_api_call(
        self, cb: Callable[[], Any], is_internal: bool = False
    ) -&gt; Any:
        if self._api_zone.get():
            return await cb()
        task = asyncio.current_task(self._loop)
        st: List[inspect.FrameInfo] = getattr(task, "__pw_stack__", inspect.stack())
        parsed_st = _extract_stack_trace_information_from_stack(st, is_internal)
        self._api_zone.set(parsed_st)
        try:
            return await cb()
        except Exception as error:
&gt;           raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
E           playwright._impl._errors.Error: BrowserType.launch: Executable doesn't exist at /home/vtkachenko/.cache/ms-playwright/chromium-1112/chrome-linux/chrome
E           ╔════════════════════════════════════════════════════════════╗
E           ║ Looks like Playwright was just installed or updated.       ║
E           ║ Please run the following command to download new browsers: ║
E           ║                                                            ║
E           ║     playwright install                                     ║
E           ║                                                            ║
E           ║ &lt;3 Playwright Team                                         ║
E           ╚════════════════════════════════════════════════════════════╝

../../venv/lib/python3.8/site-packages/playwright/_impl/_connection.py:513: Error</error></testcase><testcase classname="tests.test_goto_py_page" name="test_thir3d_test[chromium]" time="0.005"><error message="failed on setup with &quot;playwright._impl._errors.Error: BrowserType.launch: Executable doesn't exist at /home/vtkachenko/.cache/ms-playwright/chromium-1112/chrome-linux/chrome&#10;╔════════════════════════════════════════════════════════════╗&#10;║ Looks like Playwright was just installed or updated.       ║&#10;║ Please run the following command to download new browsers: ║&#10;║                                                            ║&#10;║     playwright install                                     ║&#10;║                                                            ║&#10;║ &lt;3 Playwright Team                                         ║&#10;╚════════════════════════════════════════════════════════════╝&quot;">launch_browser = &lt;function launch_browser.&lt;locals&gt;.launch at 0x7ff67982a670&gt;

&gt;   ???

/home/vtkachenko/Projects/studu/venv/lib/python3.8/site-packages/pytest_playwright/pytest_playwright.py:220: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/home/vtkachenko/Projects/studu/venv/lib/python3.8/site-packages/pytest_playwright/pytest_playwright.py:212: in launch
    ???
../../venv/lib/python3.8/site-packages/playwright/sync_api/_generated.py:13914: in launch
    self._sync(
../../venv/lib/python3.8/site-packages/playwright/_impl/_browser_type.py:94: in launch
    Browser, from_channel(await self._channel.send("launch", params))
../../venv/lib/python3.8/site-packages/playwright/_impl/_connection.py:59: in send
    return await self._connection.wrap_api_call(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = &lt;playwright._impl._connection.Connection object at 0x7ff67a36dcd0&gt;
cb = &lt;function Channel.send.&lt;locals&gt;.&lt;lambda&gt; at 0x7ff679897b80&gt;
is_internal = False

    async def wrap_api_call(
        self, cb: Callable[[], Any], is_internal: bool = False
    ) -&gt; Any:
        if self._api_zone.get():
            return await cb()
        task = asyncio.current_task(self._loop)
        st: List[inspect.FrameInfo] = getattr(task, "__pw_stack__", inspect.stack())
        parsed_st = _extract_stack_trace_information_from_stack(st, is_internal)
        self._api_zone.set(parsed_st)
        try:
            return await cb()
        except Exception as error:
&gt;           raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
E           playwright._impl._errors.Error: BrowserType.launch: Executable doesn't exist at /home/vtkachenko/.cache/ms-playwright/chromium-1112/chrome-linux/chrome
E           ╔════════════════════════════════════════════════════════════╗
E           ║ Looks like Playwright was just installed or updated.       ║
E           ║ Please run the following command to download new browsers: ║
E           ║                                                            ║
E           ║     playwright install                                     ║
E           ║                                                            ║
E           ║ &lt;3 Playwright Team                                         ║
E           ╚════════════════════════════════════════════════════════════╝

../../venv/lib/python3.8/site-packages/playwright/_impl/_connection.py:513: Error</error></testcase></testsuite></testsuites>